# Generated by Django 3.1.4 on 2021-03-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='to_team_member',
        ),
    ]
