# Generated by Django 3.1.4 on 2020-12-26 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='editable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_editability', to='main.visibilitysetting'),
        ),
        migrations.AddField(
            model_name='task',
            name='milestone_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='milestone_editability', to='main.visibilitysetting'),
        ),
        migrations.AddField(
            model_name='task',
            name='milestones',
            field=models.ManyToManyField(to='main.Milestone'),
        ),
        migrations.AlterField(
            model_name='task',
            name='visibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_visibility', to='main.visibilitysetting'),
        ),
    ]
