# Generated by Django 3.1.4 on 2020-12-26 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201226_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='admins',
        ),
        migrations.AddField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(related_name='team_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
