# Generated by Django 3.1.4 on 2020-12-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201227_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
