# Generated by Django 3.1.4 on 2020-12-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
