# Generated by Django 3.1.4 on 2021-01-11 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210111_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
