# Generated by Django 3.1.4 on 2021-02-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210207_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='main.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='to_team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_member', to='main.team'),
        ),
    ]
