# Generated by Django 3.1.4 on 2021-02-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210207_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_team',
            field=models.ForeignKey(blank=True, default=89, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='main.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='to_team_member',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_member', to='main.team'),
            preserve_default=False,
        ),
    ]
